# Generated by Django 5.2.6 on 2025-10-07 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='telephone',
            field=models.CharField(default=0, max_length=15),
            preserve_default=False,
        ),
    ]
