# Generated by Django 5.2.6 on 2025-10-09 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_commande_telephone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='prix',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
