# Generated by Django 5.2.6 on 2026-02-17

import django.db.models.deletion
import django.utils.timezone
import secrets
from django.conf import settings
from django.db import migrations, models


def populate_references(apps, schema_editor):
    Commande = apps.get_model("menu", "Commande")
    for commande in Commande.objects.filter(reference=""):
        prefix = django.utils.timezone.now().strftime("PM%y%m%d")
        while True:
            candidate = f"{prefix}{secrets.token_hex(2).upper()}"
            if not Commande.objects.filter(reference=candidate).exists():
                commande.reference = candidate
                commande.save(update_fields=["reference"])
                break


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0003_alter_pizza_prix"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="commande",
            name="notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="commande",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("cash", "Paiement a la livraison"),
                    ("mobile_money", "Mobile money"),
                    ("carte", "Carte bancaire"),
                ],
                db_index=True,
                default="cash",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="commande",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("pending", "En attente"),
                    ("paid", "Paye"),
                    ("failed", "Echoue"),
                    ("refunded", "Rembourse"),
                ],
                db_index=True,
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="commande",
            name="reference",
            field=models.CharField(blank=True, db_index=True, max_length=20),
        ),
        migrations.AddField(
            model_name="commande",
            name="status",
            field=models.CharField(
                choices=[
                    ("nouvelle", "Nouvelle"),
                    ("preparation", "En preparation"),
                    ("livraison", "En livraison"),
                    ("livree", "Livree"),
                    ("annulee", "Annulee"),
                ],
                db_index=True,
                default="nouvelle",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="commande",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="commande",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="commandes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="commandeitem",
            name="prix",
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.RunPython(populate_references, migrations.RunPython.noop),
    ]
