# Generated by Django 5.2.6 on 2026-03-07 17:10

import secrets
from decimal import Decimal

import django.core.validators
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def ensure_unique_references(apps, schema_editor):
    del schema_editor
    Commande = apps.get_model("menu", "Commande")
    seen = set()

    def next_reference():
        prefix = django.utils.timezone.now().strftime("PM%y%m%d")
        while True:
            candidate = f"{prefix}{secrets.token_hex(3).upper()}"
            if candidate not in seen and not Commande.objects.filter(reference=candidate).exists():
                seen.add(candidate)
                return candidate

    for commande in Commande.objects.order_by("id"):
        normalized_reference = (commande.reference or "").strip().upper()

        if not normalized_reference or normalized_reference in seen:
            commande.reference = next_reference()
            commande.save(update_fields=["reference"])
            continue

        if normalized_reference != commande.reference:
            commande.reference = normalized_reference
            commande.save(update_fields=["reference"])

        seen.add(normalized_reference)


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0004_commande_status_payment_user_reference"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="categorie",
            options={"ordering": ("nom",)},
        ),
        migrations.AlterModelOptions(
            name="commande",
            options={"ordering": ("-date_commande", "-id")},
        ),
        migrations.AlterModelOptions(
            name="commandeitem",
            options={"ordering": ("pizza_nom",)},
        ),
        migrations.AlterModelOptions(
            name="pizza",
            options={"ordering": ("nom",)},
        ),
        migrations.RunPython(ensure_unique_references, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="commande",
            name="reference",
            field=models.CharField(blank=True, db_index=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name="commande",
            name="telephone",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="commande",
            name="total",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=8,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
        ),
        migrations.AlterField(
            model_name="commandeitem",
            name="prix",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=8,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
        ),
        migrations.AlterField(
            model_name="commandeitem",
            name="quantite",
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name="pizza",
            name="prix",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=8,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
        ),
        migrations.AddIndex(
            model_name="commande",
            index=models.Index(fields=["date_commande"], name="menu_comman_date_co_318cb9_idx"),
        ),
        migrations.AddIndex(
            model_name="commande",
            index=models.Index(fields=["status", "payment_status"], name="menu_comman_status_18e460_idx"),
        ),
        migrations.AddIndex(
            model_name="pizza",
            index=models.Index(fields=["categorie", "nom"], name="menu_pizza_categor_db69a7_idx"),
        ),
        migrations.AddConstraint(
            model_name="commande",
            constraint=models.CheckConstraint(condition=models.Q(("total__gte", 0)), name="commande_total_gte_0"),
        ),
        migrations.AddConstraint(
            model_name="commandeitem",
            constraint=models.CheckConstraint(condition=models.Q(("prix__gte", 0)), name="commandeitem_prix_gte_0"),
        ),
        migrations.AddConstraint(
            model_name="commandeitem",
            constraint=models.CheckConstraint(condition=models.Q(("quantite__gte", 1)), name="commandeitem_quantite_gte_1"),
        ),
    ]
